catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import CategoryListView, CategoryCreateView, ProductListView, \
    ProductCreateView, ProductDetailView, FeedbackCreateView, FeedbackListView, BlogListView, \
    BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, ProductDeleteView, ProductUpdateView

from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', CategoryListView.as_view(), name='category'),
    path('product/', ProductListView.as_view(), name='product'),
    path('messages/', FeedbackListView.as_view(), name='messages'),
    path('blog/', BlogListView.as_view(), name='blog'),

    path('product/<int:pk>/', cache_page(30)(ProductDetailView.as_view()), name='product-detail'),
    path('blog/<str:slug>/', BlogDetailView.as_view(), name='blog-detail'),

    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product-update'),
    path('blog/<str:slug>/update/', BlogUpdateView.as_view(), name='blog-update'),

    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product-delete'),
    path('blog/<str:slug>/delete/', BlogDeleteView.as_view(), name='blog-delete'),

    path('category-create/', CategoryCreateView.as_view(), name='category-create'),
    path('product-create/', ProductCreateView.as_view(), name='product-create'),
    path('feedback-create/', FeedbackCreateView.as_view(), name='feedback-create'),
    path('blog-create/', BlogCreateView.as_view(), name='blog-create'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.forms import CustomAuthenticationForm
from users.views import CountryCreateView, CountryListView, CountryUpdateView, CountryDetailView, CountryDeleteView, \
    RegisterView, ProfileView, Verification, generate_new_password

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(form_class=CustomAuthenticationForm, template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/verification/<int:v_cod>/', Verification.as_view(), name='verification'),
    path('profile/genpassword/', generate_new_password, name='genpassword'),
    path('country/create/', CountryCreateView.as_view(), name='country-create'),
    path('country/<int:pk>/update/', CountryUpdateView.as_view(), name='country-update'),
    path('country/<int:pk>/delete/', CountryDeleteView.as_view(), name='country-delete'),
    path('country/list/', CountryListView.as_view(), name='country-list'),
    path('country/<int:pk>/', CountryDetailView.as_view(), name='country-detail'),
]

catalog/models.py
from django.db import models, transaction
from config.settings import AUTH_USER_MODEL as AU_MODEL


NULLABLE = {'null': True, 'blank': True}


class Category(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')

    def __str__(self):
        return f'{self.name} - {self.description}'

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'
        ordering = ('name',)


class Product(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')
    preview = models.ImageField(upload_to='products/', verbose_name='превью', **NULLABLE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name='категория')
    price = models.IntegerField(verbose_name='цена')
    created_date = models.DateTimeField(verbose_name='дата создания')
    last_modified_date = models.DateTimeField(verbose_name='дата изменения')

    creator = models.ForeignKey(AU_MODEL, on_delete=models.SET_NULL, verbose_name='создатель', **NULLABLE)

    def __str__(self):
        return f'{self.name} {self.category} {self.price}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'
        ordering = ('name',)


class Feedback(models.Model):
    name = models.CharField(max_length=150, verbose_name='Имя')
    phone = models.CharField(max_length=25, verbose_name='Телефон')
    email = models.CharField(max_length=100, verbose_name='Почта')
    message = models.TextField(verbose_name='Сообщение')

    def __str__(self):
        return f'{self.name}: {self.message[:30]}'

    class Meta:
        verbose_name = 'Отзыв'
        verbose_name_plural = 'Отзывы'


class Blog(models.Model):
    title = models.CharField(max_length=150, verbose_name='заголовок')
    slug = models.CharField(max_length=200, verbose_name='ЧПУ')
    content = models.TextField(verbose_name='Содержимое')
    preview = models.ImageField(upload_to='blogs/', verbose_name='превью', **NULLABLE)
    created_date = models.DateTimeField(verbose_name='дата создания')
    is_public = models.BooleanField(default=True, verbose_name='опубликовано или нет')
    views_count = models.IntegerField(default=0, verbose_name='количество просмотров')

    def __str__(self):
        return f'{self.title} {self.content[:50]}'

    class Meta:
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'


class Version(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE, verbose_name='Продукт')
    ver_number = models.CharField(max_length=10, verbose_name='Номер версии')
    ver_name = models.CharField(max_length=100, verbose_name='Название версии')
    is_current_version = models.BooleanField(verbose_name='Актуальная версия')

    def save(self, *args, **kwargs):
        if not self.is_current_version:
            return super(Version, self).save(*args, **kwargs)
        with transaction.atomic():
            Version.objects.filter(
                is_current_version=True).update(is_current_version=False)
            return super(Version, self).save(*args, **kwargs)

    def __str__(self):
        return f'{self.product} версия {self.ver_number}'

    class Meta:
        verbose_name = 'Версия'
        verbose_name_plural = 'Версии'

catalog/forms.py
from django import forms

from catalog.models import Product, Version, Feedback

words = ['казино', 'криптовалюта', 'крипта', 'биржа', 'дешево', 'бесплатно', 'обман', 'полиция', 'радар']


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class ProductForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Product
        exclude = ['creator']

    def clean_name(self):
        """Валидация поля name"""
        cleaned_data = self.cleaned_data['name']
        for word in words:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f'Запрещено использовать слово {cleaned_data}')
        return cleaned_data

    def clean_description(self):
        """Валидация поля description"""
        cleaned_data = self.cleaned_data['description']
        for word in words:
            if word in cleaned_data.lower():
                raise forms.ValidationError(f'Запрещено использовать слово {cleaned_data}')
        return cleaned_data


class VersionForm(forms.ModelForm):

    class Meta:
        model = Version
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name == 'is_current_version':
                continue
            field.widget.attrs['class'] = 'form-control'


class FeedbackForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Feedback
        fields = '__all__'

catalog/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.forms import inlineformset_factory
from slugify import slugify
from django.urls import reverse_lazy, reverse
from django.views.generic import ListView, CreateView, DetailView, UpdateView, DeleteView

from catalog.forms import ProductForm, VersionForm, FeedbackForm
from catalog.models import Product, Category, Feedback, Blog, Version


# Category:


class CategoryCreateView(LoginRequiredMixin, CreateView):
    model = Category
    fields = ('name', 'description')
    success_url = reverse_lazy('catalog:category')


class CategoryListView(ListView):
    model = Category


# Product:


class ProductCreateView(LoginRequiredMixin, CreateView):
    model = Product
    form_class = ProductForm
    success_url = reverse_lazy('catalog:product')

    def form_valid(self, form):
        self.object = form.save()
        self.object.creator = self.request.user
        self.object.save()

        return super().form_valid(form)


class ProductUpdateView(LoginRequiredMixin, UpdateView):
    model = Product
    form_class = ProductForm

    def get_success_url(self):
        return reverse('catalog:product-update', args=[self.kwargs.get('pk')])

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)
        VersionFormset = inlineformset_factory(Product, Version, form=VersionForm, extra=1)
        if self.request.method == 'POST':
            formset = VersionFormset(self.request.POST, instance=self.object)
        else:
            formset = VersionFormset(instance=self.object)

        context_data['formset'] = formset

        return context_data

    def form_valid(self, form):

        context_data = self.get_context_data()
        formset = context_data['formset']
        self.object = form.save()

        if formset.is_valid():
            formset.instance = self.object
            formset.save()

        return super().form_valid(form)


class ProductListView(LoginRequiredMixin, ListView):
    model = Product


class ProductDetailView(LoginRequiredMixin, DetailView):
    model = Product


class ProductDeleteView(LoginRequiredMixin, DeleteView):
    model = Product
    success_url = reverse_lazy('catalog:product')


# Feedback


class FeedbackCreateView(CreateView):
    model = Feedback
    form_class = FeedbackForm
    success_url = reverse_lazy('catalog:category')


class FeedbackListView(LoginRequiredMixin, ListView):
    model = Feedback


# Blog:


class BlogCreateView(LoginRequiredMixin, CreateView):
    model = Blog
    fields = ('title', 'content', 'preview', 'created_date', 'is_public', 'views_count',)
    success_url = reverse_lazy('catalog:blog')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
            return super().form_valid(form)


class BlogListView(ListView):
    model = Blog

    def get_queryset(self):
        """Фильтрация по флагу опубликовано"""
        queryset = super().get_queryset()
        queryset = queryset.filter(is_public=True)
        return queryset


class BlogDetailView(DetailView):
    model = Blog

    def get_object(self, queryset=None):
        """Счетчик просмотров"""
        self.object = super().get_object(queryset)
        self.object.views_count += 1
        self.object.save()
        return self.object


class BlogUpdateView(LoginRequiredMixin, UpdateView):
    model = Blog
    fields = ('title', 'content', 'preview', 'created_date', 'is_public', 'views_count',)
    success_url = reverse_lazy('catalog:blog')

    def form_valid(self, form):
        if form.is_valid():
            new_blog = form.save()
            new_blog.slug = slugify(new_blog.title)
            new_blog.save()
            return super().form_valid(form)

    def get_success_url(self):
        new_url = super().get_success_url()
        new_url += self.object.slug
        return new_url


class BlogDeleteView(LoginRequiredMixin, DeleteView):
    model = Blog
    success_url = reverse_lazy('catalog:blog')

catalog/templates/catalog/includes/inc_main_menu.html
<div class="d-flex flex-column flex-shrink-0 p-3 text-bg-dark" style="width: 280px;">
    <a href="{% url 'catalog:category' %}"
       class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <svg class="bi pe-none me-2" width="40" height="32">
            <use href="#bootstrap"></use>
        </svg>
        <span class="fs-4">Мой сайт.ру</span>
    </a>
    <hr>
    <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="{% url 'catalog:category' %}" class="nav-link active" aria-current="page">
                <svg class="bi pe-none me-2" width="16" height="16">
                    <use href="#home"></use>
                </svg>
                Каталог
            </a>
        </li>
        <li>
            <a href="{% url 'users:country-list' %}" class="nav-link text-white">
                <svg class="bi pe-none me-2" width="16" height="16">
                    <use href="#speedometer2"></use>
                </svg>
                Страны
            </a>
        </li>
        <li>
            <a href="{% url 'catalog:blog' %}" class="nav-link text-white">
                <svg class="bi pe-none me-2" width="16" height="16">
                    <use href="#table"></use>
                </svg>
                Блог
            </a>
        </li>
        <li>
            <a href="{% url 'catalog:messages' %}" class="nav-link text-white">
                <svg class="bi pe-none me-2" width="16" height="16">
                    <use href="#grid"></use>
                </svg>
                Сообщения FB
            </a>
        </li>
        <li>
            <a href="{% url 'catalog:feedback-create' %}" class="nav-link text-white">
                <svg class="bi pe-none me-2" width="16" height="16">
                    <use href="#people-circle"></use>
                </svg>
                Контакты
            </a>
        </li>
    </ul>
    <hr>
    <div class="dropdown">
        <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
           data-bs-toggle="dropdown" aria-expanded="false">
            <img src="https://github.com/mdo.png" alt="" width="32" height="32" class="rounded-circle me-2">
            <strong>
                {% if user.is_authenticated %}
                    {{ user }}
                {% else %}
                    Аутентификация
                {% endif %}
            </strong>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow">

            {% if user.is_authenticated %}
                <li><a class="dropdown-item" href="{% url 'admin:index' %}">Админка</a></li>
                <li><a class="dropdown-item" href="{% url 'users:profile' %}">Профиль</a></li>
            {% else %}
                <li><a class="dropdown-item" href="{% url 'users:login' %}">Войти</a></li>
            {% endif %}

            <li>
                <hr class="dropdown-divider">
            </li>

            <li>
                {% if user.is_authenticated %}
                    <a class="dropdown-item" href="{% url 'users:logout' %}">Выйти</a>
                {% else %}
                    <a class="dropdown-item" href="{% url 'users:register' %}">Регистрация</a>
                {% endif %}
            </li>
        </ul>
    </div>
</div>