catalog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from catalog.views import CategoryListView, CategoryCreateView, ProductListView, \
    ProductCreateView, ProductDetailView, FeedbackCreateView, FeedbackListView, BlogListView, \
    BlogCreateView, BlogDetailView, BlogUpdateView, BlogDeleteView, ProductDeleteView, ProductUpdateView

from catalog.apps import CatalogConfig

app_name = CatalogConfig.name

urlpatterns = [
    path('', CategoryListView.as_view(), name='category'),
    path('product/', ProductListView.as_view(), name='product'),
    path('messages/', FeedbackListView.as_view(), name='messages'),
    path('blog/', BlogListView.as_view(), name='blog'),

    path('product/<int:pk>/', cache_page(30)(ProductDetailView.as_view()), name='product-detail'),
    path('blog/<str:slug>/', BlogDetailView.as_view(), name='blog-detail'),

    path('product/<int:pk>/update/', ProductUpdateView.as_view(), name='product-update'),
    path('blog/<str:slug>/update/', BlogUpdateView.as_view(), name='blog-update'),

    path('product/<int:pk>/delete/', ProductDeleteView.as_view(), name='product-delete'),
    path('blog/<str:slug>/delete/', BlogDeleteView.as_view(), name='blog-delete'),

    path('category-create/', CategoryCreateView.as_view(), name='category-create'),
    path('product-create/', ProductCreateView.as_view(), name='product-create'),
    path('feedback-create/', FeedbackCreateView.as_view(), name='feedback-create'),
    path('blog-create/', BlogCreateView.as_view(), name='blog-create'),
]

config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('catalog.urls', namespace='catalog')),
    path('users/', include('users.urls', namespace='users')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LoginView, LogoutView
from django.urls import path

from users.forms import CustomAuthenticationForm
from users.views import CountryCreateView, CountryListView, CountryUpdateView, CountryDetailView, CountryDeleteView, \
    RegisterView, ProfileView, Verification, generate_new_password

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(form_class=CustomAuthenticationForm, template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('<int:pk>/verification/<int:v_cod>/', Verification.as_view(), name='verification'),
    path('profile/genpassword/', generate_new_password, name='genpassword'),
    path('country/create/', CountryCreateView.as_view(), name='country-create'),
    path('country/<int:pk>/update/', CountryUpdateView.as_view(), name='country-update'),
    path('country/<int:pk>/delete/', CountryDeleteView.as_view(), name='country-delete'),
    path('country/list/', CountryListView.as_view(), name='country-list'),
    path('country/<int:pk>/', CountryDetailView.as_view(), name='country-detail'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

from catalog.models import NULLABLE


class Country(models.Model):
    country = models.CharField(max_length=40, verbose_name='страна')
    description = models.TextField(max_length=200, verbose_name='описание')
    flag = models.ImageField(upload_to='users/country/', verbose_name='превью', **NULLABLE)

    def __str__(self):
        return f'{self.country}'

    class Meta:
        verbose_name = 'Страна'
        verbose_name_plural = 'Страны'


class User(AbstractUser):

    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)
    avatar = models.ImageField(upload_to='users/', verbose_name='аватар', **NULLABLE)
    country = models.ForeignKey(Country, on_delete=models.PROTECT, verbose_name='страна')
    verification_code = models.IntegerField(verbose_name='Код верификации', **NULLABLE)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

users/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm

from catalog.forms import StyleFormMixin
from users.models import Country, User


class CustomAuthenticationForm(AuthenticationForm):

    def __init__(self, request=None, *args, **kwargs):
        super().__init__(request, *args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(StyleFormMixin, UserCreationForm):

    class Meta:
        model = User
        fields = ('email', 'country', 'password1', 'password2')


class UserProfileForm(UserChangeForm):

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'country', 'phone', 'avatar')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'
        self.fields['password'].widget = forms.HiddenInput()


class CountryForm(StyleFormMixin, forms.ModelForm):

    class Meta:
        model = Country
        fields = '__all__'

users/views.py
from random import randint
from django.core.mail import send_mail
from django.shortcuts import redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, UpdateView, DetailView, DeleteView

from users.forms import CountryForm, UserRegisterForm, UserProfileForm
from users.models import Country, User


def gen_secret():
    return ''.join([str(randint(0, 9)) for _ in range(8)])

# Country


class CountryCreateView(CreateView):
    model = Country
    form_class = CountryForm
    success_url = reverse_lazy('users:country-list')


class CountryUpdateView(UpdateView):
    model = Country
    form_class = CountryForm
    success_url = reverse_lazy('users:country-list')


class CountryDeleteView(DeleteView):
    model = Country
    success_url = reverse_lazy('users:country-list')


class CountryDetailView(DetailView):
    model = Country


class CountryListView(ListView):
    model = Country


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):

        new_user = form.save()
        new_user.verification_code = gen_secret()
        new_user.is_active = False
        new_user.save()

        send_mail(
            'Регистрация на v-petrenko.ru',
            f'''Привет, вот твоя ссылка для подтверждения регистрации:
             vds.v-petrenko.ru/users/{new_user.pk}/verification/{new_user.verification_code}/''',
            'admin@v-petrenko.ru',
            [new_user.email],
            fail_silently=False,
        )

        return super().form_valid(form)


class Verification(DetailView):
    model = User
    template_name = 'users/verification.html'

    def get_queryset(self):
        """Верификация"""

        queryset = super().get_queryset()

        if User.objects.filter(pk=self.kwargs['pk']).get().verification_code == self.kwargs['v_cod']:
            User.objects.filter(pk=self.kwargs['pk']).update(is_active=True)

        return queryset


class ProfileView(UpdateView):
    model = User
    form_class = UserProfileForm
    success_url = reverse_lazy('users:profile')

    def get_object(self, queryset=None):
        """Чтобы не передавать во view pk"""
        return self.request.user


def generate_new_password(request):
    new_password = gen_secret()

    send_mail(
        'Сброс пароля на v-petrenko.ru',
        f'''Привет, твой новый пароль: {new_password}''',
        'admin@v-petrenko.ru',
        [request.user.email],
        fail_silently=False,
    )

    request.user.set_password(new_password)
    request.user.save()
    return redirect(reverse('catalog:category'))

users/templates/users/country_confirm_delete.html
{% extends 'catalog/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Удаление!</h1>
            <p class="fs-5 text-body-secondary">Ниже представлена форма для подтверждения удаления.</p>
        </div>
    </header>

    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post">
                            {% csrf_token %}
                                <p>Вы действительно хотите удалить страну? </p>
                                <button type="submit" class="btn btn-danger">Подтвердить</button>
                                <a href="{% url 'catalog:blog' %}" class="btn btn-warning">Отмена</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/country_detail.html
{% extends 'catalog/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Страна</h1>
            <p class="fs-5 text-body-secondary">Просмотр Страны.</p>
        </div>
    </header>

    <main class="row">
        <div class="row text-center">

            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-header py-3">
                    <h4 class="my-0 fw-normal">{{ object.country|title }}</h4>
                </div>
                <div class="card-body">
                    <p>
                        {{ object.description }}
                    </p>
                    {% if object.preview %}
                        <img src="{{ object.preview|media_path }}" alt="Изображение - {{ object.title|lower }}">
                    {% endif %}
                    <div class="row">
                        <div class="col-6">
                            <a href="{% url 'users:country-update' object.pk %}" class="w-75 mb-2 btn btn-primary">Редактировать</a>
                        </div>
                        <div class="col-6">
                            <a href="{% url 'users:country-delete' object.pk %}" class="w-75 mb-2 btn btn-danger">Удалить</a>
                        </div>
                    </div>


                </div>

                <div class="card-footer">Просмотры: {{ object.country }} </div>
            </div>

        </div>
    </main>
{% endblock %}

users/templates/users/country_form.html
{% extends 'catalog/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Страна</h1>
            <p class="fs-5 text-body-secondary">
                {% if object %}
                    Изменение
                {% else %}
                    Создание
                {% endif %}
                Страны.</p>
        </div>
    </header>

    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            {% if object %}
                                <button type="submit" class="btn btn-primary">Изменить</button>
                            {% else %}
                                <button type="submit" class="btn btn-primary">Создать</button>
                            {% endif %}

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/country_list.html
{% extends 'catalog/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Имеющиеся страны</h1>
            <p class="fs-5 text-body-secondary">Ниже представлены страны.</p>
        </div>
    </header>

    <main class="row">
        <div class="row text-center">
            {% for object in object_list %}
                <div class="col-4">
                    <div class="card mb-4 rounded-3 shadow-sm">
                        <div class="card-header py-3">
                            <h4 class="my-0 fw-normal">{{ object.country|title }}</h4>
                        </div>
                        <div class="card-body">
                            <p>
                                {{ object.description }}
                            </p>
                            <a href="{% url 'users:country-detail' object.pk %}" class="w-100 btn btn-lg btn-primary">Подробнее</a>

                        </div>
                    </div>
                </div>
            {% endfor %}

            <div class="col-12 mb-5">
                <a class="btn btn-outline-primary" href="{% url 'users:country-create' %}">Добавить</a>
            </div>

        </div>
    </main>
{% endblock %}

users/templates/users/login.html
{% extends 'catalog/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Вход</h1>
            <p class="fs-5 text-body-secondary">Введите email и пароль.</p>
        </div>
    </header>

    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Войти</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/register.html
{% extends 'catalog/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Регистрация</h1>
            <p class="fs-5 text-body-secondary">Заполните необходимые поля.</p>
        </div>
    </header>

    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Зарегистрироваться</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/user_form.html
{% extends 'catalog/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Профиль</h1>
            <p class="fs-5 text-body-secondary">Измените необходимые поля.</p>
        </div>
    </header>

    <div class="col-12">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    <div class="card-body">
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{ form.as_p }}
                            <button type="submit" class="btn btn-primary">Сохранить</button>
                            <a href="{% url 'users:genpassword' %}" class="btn btn-danger">Сбрсить пароль</a>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

users/templates/users/verification.html
{% extends 'catalog/base.html' %}

{% load media %}

{% block content %}

    <header>
        <div class="pricing-header p-3 pb-md-4 mx-auto text-center">
            <h1 class="display-4 fw-normal text-body-emphasis">Поздравляем!</h1>
            <p class="fs-5 text-body-secondary">Вы успешно верифицировали свою учетную запись.</p>
        </div>
    </header>

    <main class="row">
        <div class="row text-center">

            <div class="card mb-4 rounded-3 shadow-sm">
                <div class="card-body">
                    <a href="{% url 'catalog:category' %}" class="btn btn-primary">Перейти на главную</a>
                </div>
            </div>
        </div>
    </main>


{% endblock %}